### ISSUE TITLE
PHP chdir function does not change the working directory for LoadLibrary inside the DLL

### ISSUE THREAD

**Issue by BorisVorontsov** [SerafimArts/opengl-demo#3]
В app.php не работает \chdir на Windows 7 x64 SP1

```
PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

**Comment by SerafimArts** [comment]
I added debug code near LoadLibrary in SDL_sysloadso.c:
```c
    char buff[MAX_PATH];
    GetCurrentDirectoryA(MAX_PATH, buff);
    SDL_Log("Directory [%s\\%s]", buff, sofile);

    void *handle = (void *) LoadLibrary(tstr);
```

Expected Output:
```bash
INFO: Directory [C:\Users\Serafim\Projects\demo\USER32.DLL]
INFO: Directory [C:\Users\Serafim\Projects\demo\SHCORE.DLL]
INFO: Directory [C:\Users\Serafim\Projects\demo\vendor\serafim\ffi-sdl-image\bin\x64\libpng16-16.dll]
INFO: Directory [C:\Users\Serafim\Projects\demo\vendor\serafim\ffi-sdl\bin\x64\OPENGL32.DLL]
INFO: Directory [C:\Users\Serafim\Projects\demo\vendor\serafim\ffi-sdl\bin\x64\D3D9.DLL]
INFO: Directory [C:\Users\Serafim\Projects\demo\vendor\serafim\ffi-sdl\bin\x64\D3D9.DLL]
INFO: Directory [C:\Users\Serafim\Projects\demo\vendor\serafim\ffi-sdl\bin\x64\imm32.dll]
```

However, in some cases the directory does not change:

```bash
INFO: Directory [C:\Users\Serafim\Projects\demo\USER32.DLL]
INFO: Directory [C:\Users\Serafim\Projects\demo\SHCORE.DLL]
INFO: Directory [C:\Users\Serafim\Projects\demo\libpng16-16.dll]

Error: Failed loading libpng16-16.dll: The specified module could no
t be found
```

This is not the first such case.

**Comment by SerafimArts** [comment]
A handy example that might try to reproduce the error:

[test.zip](https://github.com/SerafimArts/opengl-demo/files/4409145/test.zip)

Example:
```php
<?php

$sdl = FFI::cdef(file_get_contents(__DIR__ . '/sdl.h'), __DIR__ . '/bin/SDL2.dll');
$image = FFI::cdef(file_get_contents(__DIR__ . '/image.h'), __DIR__ . '/bin/img/SDL2_image.dll');

chdir(__DIR__ . '/bin/img'); // <<< Possibly a PHP bug (not working)

$surface = $image->IMG_Load(__DIR__ . '/icon.png');

if ($error = $sdl->SDL_GetError()) {
    var_dump($error);
} else {
    var_dump('ALL OK');
}
```

If successful (`chdir` works), it displays "ALL OK", otherwise, a "Failed loading libpng16-16.dll" error is thrown.

![image](https://user-images.githubusercontent.com/2461257/78031648-8009a780-736c-11ea-8d40-a429de0c7934.png)

I think this bug is somewhere in the PHP. But I can’t understand where is it.

@dstogov сan you help?

**Comment by roxblnfk** [comment]
Windows 10 
![image](https://user-images.githubusercontent.com/4152481/78032020-07efb180-736d-11ea-84a0-beaa1e2f0904.png)

**Comment by SerafimArts** [comment]
Yes, this is a problem due to ZTS version using instead of Non Thread Safe.

**Comment by SerafimArts** [comment]
Yes, this is a problem due to ZTS

**Comment by SerafimArts** [comment]
Bug report: https://bugs.php.net/bug.php?id=79439

**Comment by SerafimArts** [comment]
Because this bug was not considered a bug, so I had to come up with a workaround: https://github.com/SerafimArts/ffi-sdl/blob/8b8a73f48363bac90456319416768852f9e2d337/src/Loader/LibraryInformation.php#L98
