### ISSUE TITLE
Missing onScroll anotation event

### ISSUE THREAD

**Issue by bobimicroweber** [SerafimArts/opengl-demo#4]
Hello, i check this demo and its awesome. I try to make some simple game but it missing scroll event. Can you please add it?

**Comment by SerafimArts** [comment]
Well this is not an engine, but a demo. 

Annotations are just an example of how to build an architecture using popular libraries used for web development (doctrine, laravel, etc).

You can use the OnEvent annotation to receive any events. Each event has its own type: https://github.com/SerafimArts/ffi-sdl/blob/master/src/Kernel/Event/Type.php

```php
/** @OnEvent */
public function onScroll(CData $event): void
{
    if ($event->type === Type::SDL_MOUSEWHEEL) {
        echo 'Yay!';
    }
}
```

This option will suit you?

**Comment by SerafimArts** [comment]
Oh, I see you already added it yourself =)

Just in case, I added the ability to drag the map
